name: QuietCraft
version: 0.0001
author: Tim Engler
main: com.rareventure.quietcraft.QuietCraftPlugin
database: true
commands:
  runquery:
    aliases: [rq]
    description: Runs any old query the player wants and returns the results
    usage: |
           /<command> <name> [player]
           Example: /<command> "select * from QCPlayer"
  kill:
    aliases: []
    description: Kills you
    usage: |
           /kill
           Example: /kill
              ... and you die
  gm:
    aliases: []
    description: Gives stuff
    usage: |
           /gm
           Example: /gm
              ... and you get stuff
  world:
    aliases: []
    description: Says which world you are in
    usage: |
           /world
           Example: /world
              Your world is wonky world
