name: QuietCraft
version: 0.0001
author: Tim Engler
main: com.rareventure.quietcraft.QuietCraftPlugin
database: true
commands:
  kill:
    aliases: []
    description: Kills you
    usage: |
           /kill
           Example: /kill
              ... and you die
  gm:
    aliases: []
    description: Gives stuff
    usage: |
           /gm
           Example: /gm
              ... and you get stuff
  w:
    aliases: []
    description: Says which world you are in
    usage: |
           /world
           Example: /world
              Your world is wonky world
  cp:
    aliases: []
    description: Create a portal
    usage: |
           /cp
           Example: /cp
              ...
  nb:
    aliases: []
    description: ... create a cake nearby in a random direction ..
    usage: |
           /nb [dist]
           Example: /nb
              ...
  jw:
    aliases: []
    description: ... jumps to world specified by id..
    usage: |
           /jw [world_id]
           Example: /jw
              ...
  say_mode:
    aliases: []
    description: Chatting from now on can be heard by those nearby player.
    usage: |
           /say_mode
           Example: /say_mode
              Hi guys!
  shout_mode:
    aliases: []
    description: Chatting from now on can be heard by those farther away
    usage: |
           /shout_mode
           Example: /shout_mode
              Help! Help!
  whisper_mode:
    aliases: []
    description: Chatting from now on will only be heard only by those close by
    usage: |
           /whisper_mode
           Example: /whisper_mode
              I stashed all my soul gems at ...
